# Optional Exercises <img src="images/snake.png" width="200" style="float: right;"/>

In this notebook you can find some optional exercises to test your knowledge and understanding from this week's lecture.  
In the __flipped classroom__ we will go through these exercises and offer you some possible solutions to them.

In [ ]:
import numpy as np

### Exercise 1:

#### a)
- create a 3 by 3 array, that consists only of True.

In [ ]:
# create your array

#### b)
- replace all even numbers in the array with -1

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# your code

#### c)
- create a numpy array with 100 entries, that are random samples from a Gaussian (or normal) distribution
- filter out all values below 0 and above 1

In [ ]:
# create np array from Gaussian distribution (replace the [] with your code)
gaussian_array = []

In [ ]:
# filter out all values below 0 and above 1

In [ ]:
# test if only the right values are in the array
if np.any(gaussian_array > 1) or np.any(gaussian_array < 0):
    print("something went wrong with your filter")
else: 
    print("good job!")

### Exercise 2
<img src="images/strange_pattern.png" width="200" style="float: center;"/>  

- create a function that creates this pattern for any size 
- the size is determined by two parameters hight and width

In [ ]:
def strange_pattern(hight, width):
    # your code, delete pass
    pass

In [ ]:
# test your function:
print(strange_pattern(8,8))

### Exercise 3
<img src="images/broadcasting.png" width="200" style="float: center;"/>

- create an array that looks like the one in the picture
- Tip: this can be done easily when you use broadcasting

In [ ]:
# create your array
array_3 = []

In [ ]:
# test it by printing your array
print(array_3)

### Exercise 4
- create a 1 dimenensional array that consists of all the even integers in this array:


In [16]:
input = np.array([[[[2, 6, 19], [15, 10, 23]], [[0, 9, 7], [12, 7, 16]]], [[[22, 2, 33], [11, 10, 9]], [[8, 8, 4], [7, 5, 8]]],  [[[14, 13, 29], [1, 5, 4]], [[11,13,15], [2, 0, 6]]]])

In [17]:
print(input)

[[[[ 2  6 19]
   [15 10 23]]

  [[ 0  9  7]
   [12  7 16]]]


 [[[22  2 33]
   [11 10  9]]

  [[ 8  8  4]
   [ 7  5  8]]]


 [[[14 13 29]
   [ 1  5  4]]

  [[11 13 15]
   [ 2  0  6]]]]


### Exercise 5 
<img src="images/indexing.png" width="300" style="float: center;"/>


- create an array out of the numbers in the read boxes using slicing

In [ ]:
# this is the array in the picture
advance_indexing = np.arange(121).reshape(11,11)
print(advance_indexing)

In [ ]:
# create your own array