# Numpy Arrays What - can we do with them?

[<center><img src="images/numpy_logo.png" width="400"/></center>](https://numpy.org/doc/stable/user/quickstart.html)

## Table of Contents

* [Accessing Array Elements](#aae)
    * [Indexing and Slicing](#Indx_Slic)
    * [Masking/Filtering](#Mask_Filt)
<br>
<br>
* [Math with Numpy Arrays](#mwna)
    * [Math Operators and Functions - Ufuncs](#Operators)
    * [Comparison](#Comparison)
    * [Constants](#Constants)
<br>
<br>
* [Changing Shape](#Changing_Shape)
    * [Reshape](#Reshape)
    * [Removing Dimensions](#Removing_Dimensions)
        * [Flattening](#Flattening)
        * [Squeezing](#Squeezing)
    * [Adding Dimensions](#Adding_Dimensions)
        * [Extending](#Extending)
        * [Combining Arrays](#Combining_Arrays)
        * [Repeating Arrays](#Repeating_Arrays)
    * [Aggregation](#Aggregation)
    * [Broadcasting](#Broadcasting)
<br>
<br>
* [Miscellaneous](#Miscellaneous)
    * [Repeat](#Repeat)
    * [Random Number Generation](#Random_Number_Generation)


## Imports

In [3]:
import numpy as np
print(np.__version__)

1.22.3


<a id='aae'></a>
# Accessing Array Elements

<a id='Indx_Slic'></a>
## Indexing and Slicing
To index a "single element" of a `N` dimensional `array` we can use the following syntax. <br>
`array[dim1, dim2, dim3, ..., dimN]` where `dimN` is the **index** in the **N**th dimension

In [4]:
a = np.arange(27).reshape((3,3,3))
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [5]:
a[2,0,1]

19

To access multiple elements we can **slice** an `array` with the following syntax.<br>
`array[start:stop:step]`, where `step` allows us to set a stride size.<br>

In [6]:
a = np.arange(100)
a[0:50:5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

We can also slice across multiple dimensions.

In [7]:
a = np.arange(100).reshape((10,10))
a[0:8:2, 0:10:5]


array([[ 0,  5],
       [20, 25],
       [40, 45],
       [60, 65]])

#### negative indices
We can also **index** and **slice** using **negative integers**. Negative indices while start from the back of the array and count backwards.

In [8]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a[-1]

9

In [10]:
a[-2]

8

If we define the **stride** with a **negative integer** we can reverse the array.

In [11]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

<a id='Mask_Filt'></a>
## Masking/Filtering

One way of **filtering** an `array` is by creating a **boolean mask**.<br>
A **boolean mask** should have values of either `True` `1` or `False` `0`, depending on whether or not the respective array value satisfies the given **condition**.

In [36]:
a = np.arange(10)

mask =  a%2 == 0 # condition: divisible by 2
mask

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

With the **boolean mask** we can now **filter** the `array`, which will return the values of the indices where the mask is `True`

In [37]:
a[mask]

array([0, 2, 4, 6, 8])

We can more or less use masking and filtering synonymously, but there are also [other filtering methods](https://stackoverflow.com/questions/58422690/filtering-reducing-a-numpy-array) that don't rely on masking.

<br>

<a id='Mask_Filt'></a>
# Math with Numpy Arrays

<a id='Operators'></a>
## Math Operators and Functions - Ufuncs
**Ufuncs** (short for "universal functions") are functions that operate **element-wise** on arrays.

They are called "universal" because they are able to perform a wide variety of operations on arrays of any shape or size, and are a fundamental building block of numpy's array processing capabilities.

**Ufuncs** are vectorized, meaning we offload the calculation to C, where the element-wise operations can happen for multiple elements at once. This way we don't have to rely on pythons slow looping.

In [54]:
a = np.arange(10)
b = np.arange(10)

### Mathematical operators
In mathematics we can differentiate operators and functions. Operators perform operations on objects, such as two numbers, while functions represent a relation between two objects. Some functions can also be seen as operators but not all.

#### addition

In [55]:
# same as np.add(a, 2)
a + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [58]:
a + b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### substraction

In [56]:
# same as np.subtract(a, 2)
a - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [59]:
a - b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### multiplication

In [57]:
a * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Note that multiplication with the `*` operator will also be performed element-wise and not as matrix multiplication.

In [64]:
a * b

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

#### division

In [65]:
a / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

#### matrix multiplication
The proper operator for matrix multiplication is `@`.

In [66]:
a @ b

285

### Mathematical functions

In [73]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [74]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [76]:
np.log(a[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [77]:
np.log2(a[1:])

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  ])

#### List of all **[ufuncs](https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs)**<br>


<a id='Comparison'></a>
## Comparison

### equal `==`

In [81]:
val = 1.2-1
val

0.19999999999999996

In [91]:
a = np.array([val, 2, 3, 4, 5], dtype=np.float32)
b = np.array([val, 2, 3, 8, 10], dtype=np.float64)

In [92]:
a == b

array([False,  True,  True, False, False])

Because `a` and `b` are of a different `dtype`, `val` is represented with a different "resolution"<br>
and thus it will be equal in the two arrays.

In [93]:
a[0]

0.2

In [94]:
b[0]

0.19999999999999996

To address this issue we can use `np.isclose()`

In [95]:
np.isclose(a, b)

array([ True,  True,  True, False, False])

### not equal `!=`

In [100]:
a != b

array([ True, False, False,  True,  True])

### smaller `<` greater

In [96]:
a < b

array([False, False, False,  True,  True])

In [97]:
a > b

array([ True, False, False, False, False])

### smaller/greater equal `<=` `>=`

In [98]:
a <= b

array([False,  True,  True,  True,  True])

In [99]:
a >= b

array([ True,  True,  True, False, False])

### `np.nan` != `np.nan`

In numpy, **undefined** values are not equal. 

In [101]:
np.nan == np.nan

False

to check if something is a `nan` we can use `np.isnan()`


In [119]:
np.isnan(np.nan)

True

### `all()`

To check if a given comparison is true for all array elements we can use `all()`.<br>
So we can check for example if *all* array elements are equal.

In [108]:
a = np.arange(10)
b = np.arange(10)

(a == b).all()

True

#### Watch out!

In [110]:
a = np.array([])
b = np.array([1])

In [111]:
a == b

array([], dtype=bool)

In [112]:
(a == b).all()

True

<a id='Constants'></a>
## Constants
[Numpy documentation - constants](https://numpy.org/doc/stable/reference/constants.html)

In [113]:
np.pi

3.141592653589793

In [114]:
np.e

2.718281828459045

In [116]:
np.inf > 999999999999999999999999999999999999999999999999999999

True

In [117]:
-np.inf

-inf

In [118]:
np.inf - np.inf

nan

<br>

<a id='Changing_Shape'></a>
# Changing Shape

<a id='Reshape'></a>
## Reshape

In [121]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
a.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

If we

In [124]:
a.reshape((5,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [126]:
a.reshape((4,2))

ValueError: cannot reshape array of size 10 into shape (4,2)

<a id='Removing_Dimensions'></a>
## Removing Dimensions

<a id='Flattening'></a>
### Flattening

In [130]:
a = np.ones((2,2,2))
a

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [131]:
a.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1.])

<a id='Squeezing'></a>
### Squeezing
Sometimes we have unnecessary dimensions that we want to get rid of. In such cases we can `squeeze` the array.<br>
Squeezing the array while remove dimensions that only have one element.

In [135]:
a = np.array([[[[1, 2], [3, 4], [5, 6]]]])
a

array([[[[1, 2],
         [3, 4],
         [5, 6]]]])

In [137]:
a.shape

(1, 1, 3, 2)

In [139]:
a = a.squeeze()
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [140]:
a.shape

(3, 2)

<a id='Adding_Dimensions'></a>
## Adding Dimensions

<a id='Extending'></a>
## Extending

<a id='Combining_Arrays'></a>
## Combining Arrays


<a id='Repeating_Arrays'></a>
## Repeating Arrays

<a id='Aggregation'></a>
## Aggregation

<a id='Broadcasting'></a>
## Broadcasting

<br>

<a id='Miscellaneous'></a>
# Miscellaneous

<a id='Repeat'></a>
## Repeat

<a id='Random Number Generation'></a>
## Random Number Generation