# Optional Exercises <img src="images/snake.png" width="200" style="float: right;"/>

In this notebook you can find some optional exercises to test your knowledge and understanding from this week's lecture.  
In the __flipped classroom__ we will go through these exercises and offer you some possible solutions to them.

In [2]:
import numpy as np

### Exercise 1:

#### a)
- create a 3 by 3 array, that consists only of True.

In [ ]:
# create your array

#### b)
- replace all even numbers in the array with -1

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# your code

#### c)
- create a numpy array with 100 entries, that are random samples from a Gaussian (or normal) distribution
- filter out all values below 0 and above 1

In [ ]:
# create np array from Gaussian distribution (replace the [] with your code)
gaussian_array = []

In [ ]:
# filter out all values below 0 and above 1

In [ ]:
# test if only the right values are in the array
if np.any(gaussian_array > 1) or np.any(gaussian_array < 0):
    print("something went wrong with your filter")
else: 
    print("good job!")

### Exercise 2
<img src="images/strange_pattern.png" width="200" style="float: center;"/>  

- create a function that creates this pattern for any size 
- the size is determined by two parameters hight and width

In [ ]:
def strange_pattern(hight, width):
    # your code, delete pass
    pass

In [ ]:
# test your function:
print(strange_pattern(8,8))

### Exercise 3
<img src="images/broadcasting.png" width="200" style="float: center;"/>

- create an array that looks like the one in the picture
- Tip: this can be done easily when you use broadcasting

In [ ]:
# create your array
array_3 = []

In [ ]:
# test it by printing your array
print(array_3)

### Exercise 4
- create a 1 dimenensional array that consists of all the even integers in this array:


In [3]:
arr = np.array([[[[2, 6, 19], [15, 10, 23]], [[0, 9, 7], [12, 7, 16]]], [[[22, 2, 33], [11, 10, 9]], [[8, 8, 4], [7, 5, 8]]],  [[[14, 13, 29], [1, 5, 4]], [[11,13,15], [2, 0, 6]]]])
arr

array([[[[ 2,  6, 19],
         [15, 10, 23]],

        [[ 0,  9,  7],
         [12,  7, 16]]],


       [[[22,  2, 33],
         [11, 10,  9]],

        [[ 8,  8,  4],
         [ 7,  5,  8]]],


       [[[14, 13, 29],
         [ 1,  5,  4]],

        [[11, 13, 15],
         [ 2,  0,  6]]]])

In [4]:
# do some numpy magic to create the right output

### Exercise 5 
<img src="images/indexing.png" width="300" style="float: center;"/>


- create an array out of the numbers in the read boxes using slicing

In [5]:
# this is the array in the picture
advanced_indexing = np.arange(121).reshape(11,11)
print(advanced_indexing)

[[  0   1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20  21]
 [ 22  23  24  25  26  27  28  29  30  31  32]
 [ 33  34  35  36  37  38  39  40  41  42  43]
 [ 44  45  46  47  48  49  50  51  52  53  54]
 [ 55  56  57  58  59  60  61  62  63  64  65]
 [ 66  67  68  69  70  71  72  73  74  75  76]
 [ 77  78  79  80  81  82  83  84  85  86  87]
 [ 88  89  90  91  92  93  94  95  96  97  98]
 [ 99 100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119 120]]


In [ ]:
# filter out the right colums and rows